export const NOTIFICATION_RESET = 'NOTIFICATION_RESET'
export const NOTIFICATION_SET = 'NOTIFICATION_SET'

export const SET_EVENT_NOTE = 'SET_EVENT_NOTE'
export const SET_EVENT_TYPE = 'SET_EVENT_TYPE'
